port: 3000
title:              "Wistful Leaf"
description:        "This blog has the purpose to soothe the daily challenges we face as new coders, and gently remind ourselves that everything will be okay."

url:                "https://carolinaknoll.github.io/wistful-leaf"
author:             "carolinaknoll"
email:              "carolinasknoll@gmail.com"
twitter:            "carolina_knoll"
email:              "carolinasknoll@gmail.com"
github:             "carolinaknoll"
linkedin:           "carolinaknoll"

disqus_shortname:   "carolinaknoll"

profile_image:      "/assets/img/profile-image.jpg"

paginate:           5
paginate_path:      "/page:num/"

permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-paginate